name: Generate snake game

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update snake game grid
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: KurakuDeibu
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          color_snake: '#7d3c98'  # Optional: custom snake color
          color_background: '#000000'  # Dark background

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
